name: pill_dispenser
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5  # â† Correctly placed under dependencies
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  lucide_icons_flutter: ^3.0.3
  popover: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - .env
